[2024-04-13 20:46:10,336] ERROR log_exception() L828  Exception on /pagamento [GET] - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py L828 
Traceback (most recent call last):
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\app.py", line 93, in get_pagamento
    pagamento_id = query.id
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\pydantic\main.py", line 767, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'PagamentoBuscaSchema' object has no attribute 'id'
[2024-04-13 20:46:10,475] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 20:46:10] "[35m[1mGET /pagamento?nome=conta%20agua HTTP/1.1[0m" 500 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-13 20:46:27,488] ERROR log_exception() L828  Exception on /pagamento [GET] - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py L828 
Traceback (most recent call last):
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\app.py", line 93, in get_pagamento
    pagamento_id = query.id
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\pydantic\main.py", line 767, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'PagamentoBuscaSchema' object has no attribute 'id'
[2024-04-13 20:46:27,499] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 20:46:27] "[35m[1mGET /pagamento?nome=1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-13 20:46:38,146] ERROR log_exception() L828  Exception on /pagamento [GET] - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py L828 
Traceback (most recent call last):
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\app.py", line 93, in get_pagamento
    pagamento_id = query.id
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\pydantic\main.py", line 767, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'PagamentoBuscaSchema' object has no attribute 'id'
[2024-04-13 20:46:38,177] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 20:46:38] "[35m[1mGET /pagamento?nome=conta%20agua HTTP/1.1[0m" 500 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-13 21:16:13,202] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 21:16:13] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-13 21:16:14,444] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 21:16:14] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-13 21:16:14,517] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 21:16:14] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-13 21:16:14,574] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 21:16:14] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-13 21:16:14,989] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 21:16:14] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-13 21:16:14,997] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 21:16:14] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-13 21:16:31,458] ERROR log_exception() L828  Exception on /pagamento [GET] - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py L828 
Traceback (most recent call last):
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\app.py", line 93, in get_pagamento
    pagamento_id = query.id
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\pydantic\main.py", line 767, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'PagamentoBuscaSchema' object has no attribute 'id'
