[2024-04-13 19:05:55,126] ERROR log_exception() L828  Exception on /pagamentos [GET] - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py L828 
Traceback (most recent call last):
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\app.py", line 74, in get_pagamentos
    pagamentos = session.query(Pagamento).all()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\query.py", line 2673, in all
    return self._iter().all()  # type: ignore
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\session.py", line 2306, in execute
    return self._execute_internal(
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\engine\base.py", line 3280, in connect
    return self._connection_cls(self)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\engine\base.py", line 3304, in raw_connection
    return self.pool.connect()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\pool\impl.py", line 168, in _do_get
    raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[2024-04-13 19:05:55,177] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 19:05:55] "[35m[1mGET /pagamentos HTTP/1.1[0m" 500 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-13 19:05:55,459] ERROR log_exception() L828  Exception on /pagamentos [GET] - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py L828 
Traceback (most recent call last):
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\app.py", line 74, in get_pagamentos
    pagamentos = session.query(Pagamento).all()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\query.py", line 2673, in all
    return self._iter().all()  # type: ignore
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\session.py", line 2306, in execute
    return self._execute_internal(
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\engine\base.py", line 3280, in connect
    return self._connection_cls(self)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\engine\base.py", line 3304, in raw_connection
    return self.pool.connect()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\sqlalchemy\pool\impl.py", line 168, in _do_get
    raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[2024-04-13 19:05:55,468] INFO _log() L96   127.0.0.1 - - [13/Apr/2024 19:05:55] "[35m[1mGET /pagamentos HTTP/1.1[0m" 500 - - call_trace=C:\Users\aferreira\Documents\PÓS PUC-RIO\MVP-01\back-end\api\env\lib\site-packages\werkzeug\_internal.py L96  
